#!/usr/bin/php -d memory_limit=8G
<?php
declare(strict_types=1);

$cache = [];

while ($line = fgets(STDIN)) {
	if (array_key_exists($line, $cache)) {
		echo $cache[$line];
		continue;
	}
	if (count($cache) > 10000000) {
		$cache = [];
	}

	$sems = [];

	if (preg_match_all('~(?<=^| )((activity|amount|anbo|anent|anich|anmov|anorg|anzo|ar|bar|build|cc|co[lnv]+|coll|cord|cur|dir|dance|dir|domain|dur|er|event|fight|furn|game|genre|group|inst|ism|ling|mach|meta|method|mon|occ|part|p+|per|pict|play|pos|prize|process|repr|s[ds]|sick|sit|sport|talk|temp|therapy|tube|a[cmn]|act|c[cm]|clo[HA]?|drink|f|food|fruit|geom|mat|percep|pos|sem|state|struct|system|tool|unit|wea|astro|brand|civ|disease|hum|media|org|party|j[a-z]+)(-[^\s>]+)?)(?= |$)~u', $line, $ms)) {
		$sems = array_merge($sems, $ms[1]);
		//fprintf(STDERR, "DEBUG1: %s\n", implode(', ', $ms[1]));
	}
	if (preg_match_all('~(?<=^| )([HABLV][HABLV]?[a-z]*)(?= |$)~u', $line, $ms)) {
		$sems = array_merge($sems, $ms[1]);
		//fprintf(STDERR, "DEBUG2: %s\n", implode(', ', $ms[1]));
	}
	if (preg_match_all('~(?<=^| )(fn:\S+)(?= |$)~u', $line, $ms)) {
		$sems = array_merge($sems, $ms[1]);
		//fprintf(STDERR, "DEBUG3: %s\n", implode(', ', $ms[1]));
	}

	sort($sems);
	$sems = array_unique($sems);

	$sems = implode(' ', $sems)."\n";
	echo $sems;

	$cache[$line] = $sems;
}
