#!/usr/bin/php -d memory_limit=8G
<?php
declare(strict_types=1);
require_once __DIR__.'/../_inc/lib.php';

$corp = $argv[1] ?? 'zxx_placeholder';
$lang = substr($corp, 0, 3);

while ($line = fgets(STDIN)) {
	$line = str_replace("(\t", '(', $line);
	$line = preg_replace('~([^>])\s\)~u', '$1)', $line);
	$line = preg_replace('~([^>])\s([,.;:?!])~u', '$1$2', $line);

	if ($lang === 'epo' && !preg_match('~[ŭŬĉĈĝĜĥĤĵĴŝŜ]~u', $line)) {
		$line = preg_replace('~ux~u', 'ŭ', $line);
		$line = preg_replace('~U[Xx]~u', 'Ŭ', $line);
		$line = preg_replace('~cx~u', 'ĉ', $line);
		$line = preg_replace('~C[Xx]~u', 'Ĉ', $line);
		$line = preg_replace('~gx~u', 'ĝ', $line);
		$line = preg_replace('~G[Xx]~u', 'Ĝ', $line);
		$line = preg_replace('~hx~u', 'ĥ', $line);
		$line = preg_replace('~H[Xx]~u', 'Ĥ', $line);
		$line = preg_replace('~jx~u', 'ĵ', $line);
		$line = preg_replace('~J[Xx]~u', 'Ĵ', $line);
		$line = preg_replace('~sx~u', 'ŝ', $line);
		$line = preg_replace('~S[Xx]~u', 'Ŝ', $line);
	}

	echo $line;
}
