#!/usr/bin/env python3
import gensim.models
import argparse

parser = argparse.ArgumentParser()
parser.add_argument('model')
parser.add_argument('xs')
parser.add_argument('ws')
args = parser.parse_args()

model = gensim.models.Word2Vec.load(args.model, mmap='r')
wv = model.wv
del model

xs = args.xs.split(';')
ws = args.ws.split(';')

for x in xs:
	print(x)
	for w in ws:
		val = 0

		try:
			val = wv.similarity(x, w)
		except:
			pass

		if not val:
			try:
				val = wv.similarity(x.replace(' ', '='), w.replace(' ', '='))
			except:
				pass

		print(f'\t{w}\t' + str(val))
